---
AD:
  name: Andorra
  length: 24
  format:
  - n: 8
  - c: 12
AE:
  name: United Arab Emirates
  length: 23
  format:
  - n: 3
  - n: 16
AL:
  name: Albania
  length: 28
  format:
  - n: 8
  - c: 16
AT:
  name: Austria
  length: 20
  format:
  - n: 16
AZ:
  name: Azerbaijan
  length: 28
  format:
  - c: 4
  - n: 20
BA:
  name: Bosnia and Herzegovina
  length: 20
  format:
  - n: 16
BE:
  name: Belgium
  length: 16
  format:
  - n: 12
BG:
  name: Bulgaria
  length: 22
  format:
  - a: 4
  - n: 6
  - c: 8
BH:
  name: Bahrain
  length: 22
  format:
  - a: 4
  - c: 14
BR:
  name: Brazil
  length: 29
  format:
  - n: 23
  - a: 1
  - c: 1
CH:
  name: Switzerland
  length: 21
  format:
  - n: 5
  - c: 12
CR:
  name: Costa Rica
  length: 21
  format:
  - n: 17
CY:
  name: Cyprus
  length: 28
  format:
  - n: 8
  - c: 16
CZ:
  name: Czech Republic
  length: 24
  format:
  - n: 20
DE:
  name: Germany
  length: 22
  format:
  - n: 18
DK:
  name: Denmark
  length: 18
  format:
  - n: 14
DO:
  name: Dominican Republic
  length: 28
  format:
  - a: 4
  - n: 20
EE:
  name: Estonia
  length: 20
  format:
  - n: 16
ES:
  name: Spain
  length: 24
  format:
  - n: 20
FI:
  name: Finland
  length: 18
  format:
  - n: 14
FO:
  name: Faroe Islands
  length: 18
  format:
  - n: 14
FR:
  name: France
  length: 27
  format:
  - n: 10
  - c: 11
  - n: 2
GB:
  name: United Kingdom
  length: 22
  format:
  - a: 4
  - n: 14
GE:
  name: Georgia
  length: 22
  format:
  - c: 2
  - n: 16
GI:
  name: Gibraltar
  length: 23
  format:
  - a: 4
  - c: 15
GL:
  name: Greenland
  length: 18
  format:
  - n: 14
GR:
  name: Greece
  length: 27
  format:
  - n: 7
  - c: 16
GT:
  name: Guatemala
  length: 28
  format:
  - c: 4
  - c: 20
HR:
  name: Croatia
  length: 21
  format:
  - n: 17
HU:
  name: Hungary
  length: 28
  format:
  - n: 24
IE:
  name: Ireland
  length: 22
  format:
  - c: 4
  - n: 14
IL:
  name: Israel
  length: 23
  format:
  - n: 19
IS:
  name: Iceland
  length: 26
  format:
  - n: 22
IT:
  name: Italy
  length: 27
  format:
  - a: 1
  - n: 10
  - c: 12
JO:
  name: Jordan
  length: 30
  format:
  - a: 4
  - n: 22
KW:
  name: Kuwait
  length: 30
  format:
  - a: 4
  - c: 22
KZ:
  name: Kazakhstan
  length: 20
  format:
  - n: 3
  - c: 13
LB:
  name: Lebanon
  length: 28
  format:
  - n: 4
  - c: 20
LI:
  name: Liechtenstein
  length: 21
  format:
  - n: 5
  - c: 12
LT:
  name: Lithuania
  length: 20
  format:
  - n: 16
LU:
  name: Luxembourg
  length: 20
  format:
  - n: 3
  - c: 13
LV:
  name: Latvia
  length: 21
  format:
  - a: 4
  - c: 13
MC:
  name: Monaco
  length: 27
  format:
  - n: 10
  - c: 11
  - n: 2
MD:
  name: Moldova
  length: 24
  format:
  - c: 2
  - c: 18
ME:
  name: Montenegro
  length: 22
  format:
  - n: 18
MK:
  name: Macedonia
  length: 19
  format:
  - n: 3
  - c: 10
  - n: 2
MR:
  name: Mauritania
  length: 27
  format:
  - n: 23
MT:
  name: Malta
  length: 31
  format:
  - a: 4
  - n: 5
  - c: 18
MU:
  name: Mauritius
  length: 30
  format:
  - a: 4
  - n: 19
  - a: 3
NL:
  name: Netherlands
  length: 18
  format:
  - a: 4
  - n: 10
'NO':
  name: Norway
  length: 15
  format:
  - n: 11
PK:
  name: Pakistan
  length: 24
  format:
  - c: 4
  - n: 16
PL:
  name: Poland
  length: 28
  format:
  - n: 24
PS:
  name: Palestinian territories
  length: 29
  format:
  - c: 4
  - n: 21
PT:
  name: Portugal
  length: 25
  format:
  - n: 21
QA:
  name: Qatar
  length: 29
  format:
  - a: 4
  - c: 21
RO:
  name: Romania
  length: 24
  format:
  - a: 4
  - c: 16
RS:
  name: Serbia
  length: 22
  format:
  - n: 18
SA:
  name: Saudi Arabia
  length: 24
  format:
  - n: 2
  - c: 18
SE:
  name: Sweden
  length: 24
  format:
  - n: 20
SI:
  name: Slovenia
  length: 19
  format:
  - n: 15
SK:
  name: Slovakia
  length: 24
  format:
  - n: 20
SM:
  name: San Marino
  length: 27
  format:
  - a: 1
  - n: 10
  - c: 12
TL:
  name: East Timor
  length: 23
  format:
  - n: 19
TN:
  name: Tunisia
  length: 24
  format:
  - n: 20
TR:
  name: Turkey
  length: 26
  format:
  - n: 5
  - c: 17
VG:
  name: Virgin Islands, British
  length: 24
  format:
  - c: 4
  - n: 16
XK:
  name: Kosovo
  length: 20
  format:
  - n: 4
  - n: 10
  - n: 2
